title: Content Template
description: Repository template for markdown-based skilling content
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Default layouts
defaults:
  - scope:
      path: "content"
    values:
      layout: "content"
  - scope:
      path: "README.md"
    values:
      layout: none
      published: false
  - Gemfile
  - Gemfile.lock
